// Vue/vue-acquaintance/src/components/PostForm.vue
<template>
  <form class="form" @submit.prevent>
    <h2>Create Post</h2>
    <my-input
        v-model:value="post.title"
        type="text"
        placeholder="Enter title"
    />
    <my-input
        v-model:value="post.body"
        type="text"
        placeholder="Enter body"
    />
    <my-button
        class="btn"
        @click="createPost"
    >
      Create Post
    </my-button >
  </form>
</template>

<script>

export default {
  data(){
    return {
      post: {
        title: '',
        body: ''
      }
    }
  },
  methods: {
    createPost() {
      this.post.id = Date.now();
      this.$emit('create', this.post);
      this.post = {
        title: '',
        body: ''
      };
    }
  }
}
</script>

<style scoped>

.form {
  border-radius: 5px;
  border: 2px solid #2c3e50;
  padding: 8px;
  display: flex;
  flex-direction: column;
}

</style>

// react/react-start/src/components/PostForm.jsx
import React, { useState } from 'react'
import MyInput from './UI/input/MyInput';
import MyButton from './UI/button/MyButton';

 const PostForm = ({create}) => {

    const [post, setPost] = useState({title: '', description: ''});

    const addNewPost = (e) => {
        e.preventDefault();
        const newPost = { ...post, id: Date.now() };
        setPost({title: '', description: ''});
        create(newPost);
    }

    return (
        <form>
            <MyInput 
            type='text' 
            placeholder='Title' 
            value={post.title} 
            onChange={(e) => setPost({...post, title: e.target.value})
            }/>
            <MyInput
            type='text' 
            placeholder='Description' 
            value={post.description} 
            onChange={(e) => setPost({...post, description: e.target.value})
            }/>

            <MyButton onClick={addNewPost}>Create Post</MyButton>
        </form>
    )
}

export default PostForm;
